### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by paultcochrane**
... to describe usage, installation and development instructions.

### CODE REVIEW

**Comment by reneeb** [comment]
I've just changed the way how the README file is compiled. But your changes are great, so I probably will build a Dist::Zilla plugin based on it - if you're ok with this.

**Comment by paultcochrane** [comment]
Sure, go for it :-)

**Comment by reneeb** [comment]
Here we go: https://github.com/reneeb/Dist-Zilla-Plugin-ReadmeAddDevInfo

Thanks. I've learned a lot...

**Comment by paultcochrane** [comment]
My pleasure!  Only too happy to help out :-)  Actually, I really enjoy doing stuff like this!

**Pull request closed without merging**
